### ISSUE TITLE
Is it possible to import all/selected dataframes from R environment ?

### ISSUE THREAD

**Issue by Eduardodudu** [patzaw/ReDaMoR#1]
Is it possible to import all/selected dataframes from R environment in order to start modeling?

I see that it can actually import from SQL or JSON, but I wonder if it's possible to gather the structure of dataframes from R environment and start modeling the workbench from this point on.

Thank you!

**Comment by patzaw** [comment]
The function `df_to_model()` is made for that purpose.

```
?df_to_model
example("df_to_model")
```

I hope it helps

**Comment by Eduardodudu** [comment]
Thank you! It worked!

This is amazing!

**Comment by patzaw** [comment]
Thank you
